### ISSUE TITLE
Add support for bootstrap v4 themes

### ISSUE THREAD

**Issue by xiaohanyu** [semantic-ui-forest/forest-themes#18]
It seems that bootstrap has released v4 and bootswatch has created/ported 21 themes to bootstrap v4, we need to support that.

**Comment by tarvos21** [comment]
Great, got the assignment. I have encountered one small problem related to the directory's structure.

The Bootswatch theme source files are in `forest-themes/src/themes/bootswatch/`, but in the configuration file `semantic.json`, the path for themes is defined as `src/themes/`, so that when one tries to build the themes, Bootswatch themes' source files will not be found because it's not in the root of `src/themes/`. We can either move the themes' source code upper to the root of `src/themes/`, or change the theme configuration files like `theme.config` in `forest-themes/src/theme-configs/`.

The users of this repo may also move them out by themselves.

**Comment by xiaohanyu** [comment]
@tarvos21 I agree, there're some confusions about the directory structure, that's why I've written a build script for the build process https://github.com/semantic-ui-forest/forest-themes/blob/master/build/build.js .

I'm still working on the build process to make it more intuitive. Give me some time.

**Comment by xiaohanyu** [comment]
It's almost done, thanks.
